# Generated by Django 4.1.7 on 2023-02-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='atanan',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_by',
            new_name='atayan',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='aciklama',
        ),
    ]
