# Generated by Django 4.1.7 on 2023-02-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_taskimportance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskImportance',
        ),
    ]
