# Generated by Django 4.1.7 on 2023-02-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_delete_taskimportance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='baslangic',
            field=models.DateField(default='1212-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
