# Generated by Django 4.1.7 on 2023-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_task_baslangic_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitis',
            field=models.DateField(default='1212-12-12', verbose_name='bitis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='baslangic',
            field=models.DateField(default='1212-12-12', verbose_name='baslangic'),
        ),
    ]
