# Generated by Django 4.1.7 on 2023-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_task_bitis_alter_task_baslangic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='baslangic',
            field=models.DateField(verbose_name='baslangic'),
        ),
    ]
