# Generated by Django 4.1.6 on 2023-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ek',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Gorsel'),
        ),
    ]
