# Generated by Django 4.1.6 on 2023-02-22 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_task_ek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskImportance',
        ),
    ]
