# Generated by Django 4.1.7 on 2023-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_delete_taskimportance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ek',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya Eki'),
        ),
    ]
