# Generated by Django 4.1.7 on 2023-02-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('Baslamadi', 'Baslamadi'), ('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandi', 'Tamamlandi'), ('Suresi Gecti', 'Suresi Gecti'), ('Ek Sure Talep Ediliyor', 'Ek Sure Talep Ediliyor')], default='Beklemede', max_length=25, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gorev', to='erp.task')),
            ],
        ),
    ]
