# Generated by Django 4.1.7 on 2023-03-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_checklist_task_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='aciklama',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.TextField(),
        ),
    ]
