# Generated by Django 4.1.7 on 2023-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_remove_checklist_aciklama_alter_checklist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('danger', 'Kritik'), ('warning', 'Acil'), ('primary', 'Normal')], default='Normal', max_length=25, verbose_name='Aciliyet'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tamamlandi'),
        ),
    ]
