# Generated by Django 4.1.7 on 2023-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_task_urgency_alter_checklist_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='urgency',
        ),
        migrations.AddField(
            model_name='task',
            name='aciliyet',
            field=models.CharField(choices=[('primary', 'Normal'), ('warning', 'Acil'), ('danger', 'Kritik')], default='primary', max_length=25, verbose_name='Aciliyet'),
        ),
    ]
