# Generated by Django 4.1.7 on 2023-03-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_remove_task_urgency_task_aciliyet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_by',
            new_name='team_leader',
        ),
    ]
